on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📦 Manually Install pnpm
        run: npm install -g pnpm@10

      - name: 🪡 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ⚡ Run tests
        run: pnpm run test

      - name: 🚦 Lint
        run: pnpm run lint

      - name: 🧙🏿TSC
        run: pnpm run tsc

      - name: 📥 Generate npm package
        run: pnpm run build
